### ISSUE TITLE
Duplicate of #1

### ISSUE THREAD

**Issue by Heriptik** [Yeregorix/GhostBuster#2]
Hi, i have this error spamming my console : [https://hastebin.com/agapeleyuc.md](https://hastebin.com/agapeleyuc.md)

![sponge vers](https://user-images.githubusercontent.com/37271167/119531462-39eb8080-bd84-11eb-9f6e-2bd6571a341a.png)

**Comment by Yeregorix** [comment]
The issue has been fixed in Sponge 3 days ago. Update to latest Sponge version.

**Comment by Heriptik** [comment]
I might be stupid but I don't see a new version on the sponge website
[https://www.spongepowered.org/downloads/spongeforge/stable/1.12.2](https://www.spongepowered.org/downloads/spongeforge/stable/1.12.2)

**Comment by Yeregorix** [comment]
The usual download page is currently broken. You can download latest versions here:
SpongeForge : https://github.com/SpongePowered/SpongeForge/actions?query=workflow%3A%22Build+and+Deploy%22
SpongeVanilla : https://github.com/SpongePowered/SpongeVanilla/actions?query=workflow%3A%22Build+and+Deploy%22
